[project]
name = "ami-notifications-api"
version = "0.1.0"
description = "AMI notifications API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I"] # also sort imports with an isort rule
