# Generated by Django 6.0.7 on 2026-09-21 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_device_id"),
    ]

    operations = [
        # recreate index on user_id, as a foreign key it should already be there but
        # old databases may be missing it.
        # 99fc0ecd is names_digest("registration", "user_id", length=8) (as done in
        # django _create_index_name() method).
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS registration_user_id_99fc0ecd ON registration(user_id)",
            "",
        ),
    ]
