"""
Django settings for ami project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import sentry_sdk
from dotenv import dotenv_values

import vapid_keys

CONFIG = {
    **dotenv_values(".env"),
    **dotenv_values(".env.local"),
    **dotenv_values(".env.development"),
    **dotenv_values(".env.development.local"),
    **os.environ,  # override loaded values with environment variables
}

# Generate VAPID keys for Webpush if absent
CONFIG = vapid_keys.initialize(CONFIG)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-08fl(&lb$**45l!h!n$e!n(+)$+#p-gnw-d7$msk^^73xj&#$d"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CONFIG["DEBUG"] == "true"

ALLOWED_HOSTS = [
    ".osc-fr1.scalingo.io",
    "ami-back-prod.osc-secnum-fr1.scalingo.io",
]


# Application definition

INSTALLED_APPS = [
    "channels_postgres",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "ami.authentication",
    "ami.notification",
    "ami.user",
    "ami.utils",
    "ami.api",
    "ami.partner",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ami.authentication.middleware.AMIJWTAuthCookieMiddleware",
]

ROOT_URLCONF = "ami.urls"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [
    BASE_DIR / "public" / "mobile-app" / "build",
]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
WHITENOISE_ROOT = STATIC_ROOT

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [STATIC_ROOT],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ami.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

postgres_database = dj_database_url.parse(CONFIG["DATABASE_URL"])
DATABASES = {"default": postgres_database}

# Tasks
# TODO: use a real task backend in production
TASKS = {"default": {"BACKEND": "django.tasks.backends.immediate.ImmediateBackend"}}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

APPEND_SLASH = False
PUBLIC_APP_URL = CONFIG["PUBLIC_APP_URL"]

# Cors
CORS_ALLOWED_ORIGINS = [PUBLIC_APP_URL]
CORS_ALLOW_CREDENTIALS = True


# Sentry
def before_send(event, hint):
    if "exc_info" in hint:
        _, exc_value, _ = hint["exc_info"]
        if hasattr(exc_value, "status_code") and exc_value.status_code == 401:
            return None
    return event


sentry_sdk.init(
    dsn=CONFIG.get("SENTRY_DSN", ""),
    environment=CONFIG.get("SENTRY_ENV", ""),
    before_send=before_send,  # Filter the exceptions being reported to Sentry.
)

# FranceConnect authentication
AUTH_COOKIE_JWT_NAME = "token"
AUTH_COOKIE_JWT_SECRET = CONFIG["AUTH_COOKIE_JWT_SECRET"]
assert AUTH_COOKIE_JWT_SECRET, "set a random AUTH_COOKIE_JWT_SECRET in your .env.local file"
PUBLIC_FC_AMI_CLIENT_ID = CONFIG["PUBLIC_FC_AMI_CLIENT_ID"]
FC_AMI_CLIENT_SECRET = CONFIG["FC_AMI_CLIENT_SECRET"]
PUBLIC_FC_BASE_URL = CONFIG["PUBLIC_FC_BASE_URL"]
PUBLIC_FC_PROXY = CONFIG["PUBLIC_FC_PROXY"]
PUBLIC_FC_SCOPE = CONFIG["PUBLIC_FC_SCOPE"]
PUBLIC_FC_AMI_REDIRECT_URL = CONFIG["PUBLIC_FC_AMI_REDIRECT_URL"]
PUBLIC_FC_TOKEN_ENDPOINT = CONFIG["PUBLIC_FC_TOKEN_ENDPOINT"]
PUBLIC_FC_JWKS_ENDPOINT = CONFIG["PUBLIC_FC_JWKS_ENDPOINT"]
PUBLIC_FC_USERINFO_ENDPOINT = CONFIG["PUBLIC_FC_USERINFO_ENDPOINT"]
PUBLIC_FC_AUTHORIZATION_ENDPOINT = CONFIG["PUBLIC_FC_AUTHORIZATION_ENDPOINT"]
PUBLIC_FC_SERVICE_PROVIDER_REDIRECT_URL = CONFIG["PUBLIC_FC_SERVICE_PROVIDER_REDIRECT_URL"]
PUBLIC_FC_SERVICE_PROVIDER_CLIENT_ID = CONFIG["PUBLIC_FC_SERVICE_PROVIDER_CLIENT_ID"]

# APi particulier
PUBLIC_API_PARTICULIER_BASE_URL = CONFIG["PUBLIC_API_PARTICULIER_BASE_URL"]
PUBLIC_API_PARTICULIER_QUOTIENT_ENDPOINT = CONFIG["PUBLIC_API_PARTICULIER_QUOTIENT_ENDPOINT"]
PUBLIC_API_PARTICULIER_RECIPIENT_ID = CONFIG["PUBLIC_API_PARTICULIER_RECIPIENT_ID"]

# Channels
PUBLIC_CHANNEL_UNAUTHORIZED_CODE = 4001

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_postgres.core.PostgresChannelLayer",
        "CONFIG": postgres_database,
    }
}

# VAPID keys for webpush
VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")


if DEBUG:
    ALLOWED_HOSTS += [
        "localhost",
        "127.0.0.1",
    ]
