import os

AUTH_COOKIE_JWT_SECRET = os.getenv("AUTH_COOKIE_JWT_SECRET", "")
assert AUTH_COOKIE_JWT_SECRET, "set a random AUTH_COOKIE_JWT_SECRET in your .env.local file"

SENTRY_DSN = os.getenv("SENTRY_DSN", "")
SENTRY_ENV = os.getenv("SENTRY_ENV", "")

VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
VAPID_APPLICATION_SERVER_KEY = os.getenv("VAPID_APPLICATION_SERVER_KEY", "")

# This is the folder where the svelte PWA is built statically.
HTML_DIR = "public/mobile-app/build"

PUBLIC_FC_AMI_CLIENT_ID = os.getenv("PUBLIC_FC_AMI_CLIENT_ID", "")
FC_AMI_CLIENT_SECRET = os.getenv("FC_AMI_CLIENT_SECRET", "")
PUBLIC_FC_BASE_URL = os.getenv("PUBLIC_FC_BASE_URL", "")
PUBLIC_FC_PROXY = os.getenv("PUBLIC_FC_PROXY", "")
PUBLIC_FC_SCOPE = os.getenv("PUBLIC_FC_SCOPE", "")
PUBLIC_FC_AMI_REDIRECT_URL = os.getenv("PUBLIC_FC_AMI_REDIRECT_URL", "")
PUBLIC_FC_TOKEN_ENDPOINT = os.getenv("PUBLIC_FC_TOKEN_ENDPOINT", "")
PUBLIC_FC_JWKS_ENDPOINT = os.getenv("PUBLIC_FC_JWKS_ENDPOINT", "")
PUBLIC_FC_USERINFO_ENDPOINT = os.getenv("PUBLIC_FC_USERINFO_ENDPOINT", "")
PUBLIC_FC_AUTHORIZATION_ENDPOINT = os.getenv("PUBLIC_FC_AUTHORIZATION_ENDPOINT", "")
PUBLIC_FC_SERVICE_PROVIDER_REDIRECT_URL = os.getenv("PUBLIC_FC_SERVICE_PROVIDER_REDIRECT_URL", "")
PUBLIC_FC_SERVICE_PROVIDER_CLIENT_ID = os.getenv("PUBLIC_FC_SERVICE_PROVIDER_CLIENT_ID", "")
PUBLIC_API_PARTICULIER_BASE_URL = os.getenv("PUBLIC_API_PARTICULIER_BASE_URL", "")
PUBLIC_API_PARTICULIER_QUOTIENT_ENDPOINT = os.getenv("PUBLIC_API_PARTICULIER_QUOTIENT_ENDPOINT", "")
PUBLIC_API_PARTICULIER_RECIPIENT_ID = os.getenv("PUBLIC_API_PARTICULIER_RECIPIENT_ID", "")
PUBLIC_API_DATA_EDUCATION_BASE_URL = os.getenv("PUBLIC_API_DATA_EDUCATION_BASE_URL", "")
PUBLIC_API_DATA_EDUCATION_HOLIDAYS_ENDPOINT = os.getenv(
    "PUBLIC_API_DATA_EDUCATION_HOLIDAYS_ENDPOINT", ""
)
PUBLIC_OTV_URL = os.getenv("PUBLIC_OTV_URL", "")
PUBLIC_OTV_PUBLIC_KEY = os.getenv("PUBLIC_OTV_PUBLIC_KEY", "")
OTV_PRIVATE_KEY = os.getenv("OTV_PRIVATE_KEY", "")
PUBLIC_API_URL = os.getenv("PUBLIC_API_URL", "")
PUBLIC_APP_URL = os.getenv("PUBLIC_APP_URL", "")
PUBLIC_SECTOR_IDENTIFIER_URL = os.getenv("PUBLIC_SECTOR_IDENTIFIER_URL", "")

PARTNERS_PSL_SECRET = os.getenv("PARTNERS_PSL_SECRET", "")
assert PARTNERS_PSL_SECRET, "set a random PARTNERS_PSL_SECRET in your .env.local file"
