from typing import Any

from litestar import Litestar
from litestar.testing import TestClient
from pytest_httpx import HTTPXMock


async def test_recipient_fc_hash(
    test_client: TestClient[Litestar],
) -> None:
    params = {
        "given_name": "Angela Claire Louise",
        "family_name": "DUBOIS",
        "birthdate": "1962-08-24",
        "gender": "female",
        "birthplace": "75107",
        "birthcountry": "99100",
    }
    response = test_client.get("/dev-utils/recipient-fc-hash", params=params)
    assert response.text == "4abd71ec1f581dce2ea2221cbeac7c973c6aea7bcb835acdfe7d6494f1528060"

    params.pop("birthplace")
    response = test_client.get("/dev-utils/recipient-fc-hash", params=params)
    assert response.text == "7e74df2cbebae761eccedbc24b7fe589bb83137f7808a2930031f52c73d75efe"


async def test_review_apps(
    test_client: TestClient[Litestar],
    httpx_mock: HTTPXMock,
) -> None:
    httpx_mock.add_response(
        method="GET",
        url="https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls?state=open&sort=created&per_page=100",
        json=GITHUB_JSON_RESPONSE,
    )
    response = test_client.get("/dev-utils/review-apps")
    json_data = response.json()
    assert len(json_data) == 2  # Staging + the PR returned in GITHUB_JSON_RESPONSE
    assert json_data[0]["title"] == "Staging"


async def test_review_apps_github_failure(
    test_client: TestClient[Litestar],
    httpx_mock: HTTPXMock,
) -> None:
    httpx_mock.add_response(
        method="GET",
        url="https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls?state=open&sort=created&per_page=100",
        status_code=400,
    )
    response = test_client.get("/dev-utils/review-apps")
    json_data = response.json()
    assert len(json_data) == 1  # Only the hardcoded Staging
    assert json_data[0]["title"] == "Staging"


GITHUB_JSON_RESPONSE: list[dict[str, Any]] = [
    {
        "url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/83",
        "id": 2759929411,
        "node_id": "PR_kwDOOSMCFs6kgS5D",
        "html_url": "https://github.com/numerique-gouv/ami-notifications-api/pull/83",
        "diff_url": "https://github.com/numerique-gouv/ami-notifications-api/pull/83.diff",
        "patch_url": "https://github.com/numerique-gouv/ami-notifications-api/pull/83.patch",
        "issue_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/83",
        "number": 83,
        "state": "open",
        "locked": False,
        "title": "Donne la possibilité d'avoir des noms de fichiers et non les valeurs …",
        "user": {
            "login": "edouard-gv",
            "id": 2457459,
            "node_id": "MDQ6VXNlcjI0NTc0NTk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2457459?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/edouard-gv",
            "html_url": "https://github.com/edouard-gv",
            "followers_url": "https://api.github.com/users/edouard-gv/followers",
            "following_url": "https://api.github.com/users/edouard-gv/following{/other_user}",
            "gists_url": "https://api.github.com/users/edouard-gv/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/edouard-gv/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/edouard-gv/subscriptions",
            "organizations_url": "https://api.github.com/users/edouard-gv/orgs",
            "repos_url": "https://api.github.com/users/edouard-gv/repos",
            "events_url": "https://api.github.com/users/edouard-gv/events{/privacy}",
            "received_events_url": "https://api.github.com/users/edouard-gv/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": False,
        },
        "body": "…dans les variables d'environnement de clé.",
        "created_at": "2025-08-20T14:00:11Z",
        "updated_at": "2025-08-27T13:14:35Z",
        "closed_at": None,
        "merged_at": None,
        "merge_commit_sha": None,
        "assignee": None,
        "assignees": [],
        "requested_reviewers": [],
        "requested_teams": [],
        "labels": [],
        "milestone": None,
        "draft": False,
        "commits_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/83/commits",
        "review_comments_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/83/comments",
        "review_comment_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/83/comments",
        "statuses_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/statuses/b9c987327a8f8e45648c1508faacf062637584c6",
        "head": {
            "label": "numerique-gouv:key-from-file",
            "ref": "key-from-file",
            "sha": "b9c987327a8f8e45648c1508faacf062637584c6",
            "user": {
                "login": "numerique-gouv",
                "id": 43571069,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjQzNTcxMDY5",
                "avatar_url": "https://avatars.githubusercontent.com/u/43571069?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/numerique-gouv",
                "html_url": "https://github.com/numerique-gouv",
                "followers_url": "https://api.github.com/users/numerique-gouv/followers",
                "following_url": "https://api.github.com/users/numerique-gouv/following{/other_user}",
                "gists_url": "https://api.github.com/users/numerique-gouv/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/numerique-gouv/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/numerique-gouv/subscriptions",
                "organizations_url": "https://api.github.com/users/numerique-gouv/orgs",
                "repos_url": "https://api.github.com/users/numerique-gouv/repos",
                "events_url": "https://api.github.com/users/numerique-gouv/events{/privacy}",
                "received_events_url": "https://api.github.com/users/numerique-gouv/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": False,
            },
            "repo": {
                "id": 958595606,
                "node_id": "R_kgDOOSMCFg",
                "name": "ami-notifications-api",
                "full_name": "numerique-gouv/ami-notifications-api",
                "private": False,
                "owner": {
                    "login": "numerique-gouv",
                    "id": 43571069,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQzNTcxMDY5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/43571069?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/numerique-gouv",
                    "html_url": "https://github.com/numerique-gouv",
                    "followers_url": "https://api.github.com/users/numerique-gouv/followers",
                    "following_url": "https://api.github.com/users/numerique-gouv/following{/other_user}",
                    "gists_url": "https://api.github.com/users/numerique-gouv/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/numerique-gouv/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/numerique-gouv/subscriptions",
                    "organizations_url": "https://api.github.com/users/numerique-gouv/orgs",
                    "repos_url": "https://api.github.com/users/numerique-gouv/repos",
                    "events_url": "https://api.github.com/users/numerique-gouv/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/numerique-gouv/received_events",
                    "type": "Organization",
                    "user_view_type": "public",
                    "site_admin": False,
                },
                "html_url": "https://github.com/numerique-gouv/ami-notifications-api",
                "description": "This is the AMI (Application Mobile Interministérielle) notifications API, providing entry points to create and list notifications, and to store push URLs registered from clients (web or mobile).",
                "fork": False,
                "url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api",
                "forks_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/forks",
                "keys_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/teams",
                "hooks_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/hooks",
                "issue_events_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/events{/number}",
                "events_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/events",
                "assignees_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/assignees{/user}",
                "branches_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/branches{/branch}",
                "tags_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/tags",
                "blobs_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/languages",
                "stargazers_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/stargazers",
                "contributors_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/contributors",
                "subscribers_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/subscribers",
                "subscription_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/subscription",
                "commits_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/contents/{+path}",
                "compare_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/merges",
                "archive_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/downloads",
                "issues_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues{/number}",
                "pulls_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/labels{/name}",
                "releases_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/releases{/id}",
                "deployments_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/deployments",
                "created_at": "2025-04-01T13:04:13Z",
                "updated_at": "2025-12-24T10:18:07Z",
                "pushed_at": "2025-12-24T10:21:18Z",
                "git_url": "git://github.com/numerique-gouv/ami-notifications-api.git",
                "ssh_url": "git@github.com:numerique-gouv/ami-notifications-api.git",
                "clone_url": "https://github.com/numerique-gouv/ami-notifications-api.git",
                "svn_url": "https://github.com/numerique-gouv/ami-notifications-api",
                "homepage": None,
                "size": 11018,
                "stargazers_count": 4,
                "watchers_count": 4,
                "language": "Python",
                "has_issues": True,
                "has_projects": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "has_discussions": False,
                "forks_count": 0,
                "mirror_url": None,
                "archived": False,
                "disabled": False,
                "open_issues_count": 103,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "spdx_id": "MIT",
                    "url": "https://api.github.com/licenses/mit",
                    "node_id": "MDc6TGljZW5zZTEz",
                },
                "allow_forking": True,
                "is_template": False,
                "web_commit_signoff_required": False,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 103,
                "watchers": 4,
                "default_branch": "main",
            },
        },
        "base": {
            "label": "numerique-gouv:main",
            "ref": "main",
            "sha": "45b5b31333bceacb8fc4b9c6cccd2cb63c250fac",
            "user": {
                "login": "numerique-gouv",
                "id": 43571069,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjQzNTcxMDY5",
                "avatar_url": "https://avatars.githubusercontent.com/u/43571069?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/numerique-gouv",
                "html_url": "https://github.com/numerique-gouv",
                "followers_url": "https://api.github.com/users/numerique-gouv/followers",
                "following_url": "https://api.github.com/users/numerique-gouv/following{/other_user}",
                "gists_url": "https://api.github.com/users/numerique-gouv/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/numerique-gouv/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/numerique-gouv/subscriptions",
                "organizations_url": "https://api.github.com/users/numerique-gouv/orgs",
                "repos_url": "https://api.github.com/users/numerique-gouv/repos",
                "events_url": "https://api.github.com/users/numerique-gouv/events{/privacy}",
                "received_events_url": "https://api.github.com/users/numerique-gouv/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": False,
            },
            "repo": {
                "id": 958595606,
                "node_id": "R_kgDOOSMCFg",
                "name": "ami-notifications-api",
                "full_name": "numerique-gouv/ami-notifications-api",
                "private": False,
                "owner": {
                    "login": "numerique-gouv",
                    "id": 43571069,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQzNTcxMDY5",
                    "avatar_url": "https://avatars.githubusercontent.com/u/43571069?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/numerique-gouv",
                    "html_url": "https://github.com/numerique-gouv",
                    "followers_url": "https://api.github.com/users/numerique-gouv/followers",
                    "following_url": "https://api.github.com/users/numerique-gouv/following{/other_user}",
                    "gists_url": "https://api.github.com/users/numerique-gouv/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/numerique-gouv/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/numerique-gouv/subscriptions",
                    "organizations_url": "https://api.github.com/users/numerique-gouv/orgs",
                    "repos_url": "https://api.github.com/users/numerique-gouv/repos",
                    "events_url": "https://api.github.com/users/numerique-gouv/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/numerique-gouv/received_events",
                    "type": "Organization",
                    "user_view_type": "public",
                    "site_admin": False,
                },
                "html_url": "https://github.com/numerique-gouv/ami-notifications-api",
                "description": "This is the AMI (Application Mobile Interministérielle) notifications API, providing entry points to create and list notifications, and to store push URLs registered from clients (web or mobile).",
                "fork": False,
                "url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api",
                "forks_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/forks",
                "keys_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/teams",
                "hooks_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/hooks",
                "issue_events_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/events{/number}",
                "events_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/events",
                "assignees_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/assignees{/user}",
                "branches_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/branches{/branch}",
                "tags_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/tags",
                "blobs_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/languages",
                "stargazers_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/stargazers",
                "contributors_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/contributors",
                "subscribers_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/subscribers",
                "subscription_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/subscription",
                "commits_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/contents/{+path}",
                "compare_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/merges",
                "archive_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/downloads",
                "issues_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues{/number}",
                "pulls_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/labels{/name}",
                "releases_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/releases{/id}",
                "deployments_url": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/deployments",
                "created_at": "2025-04-01T13:04:13Z",
                "updated_at": "2025-12-24T10:18:07Z",
                "pushed_at": "2025-12-24T10:21:18Z",
                "git_url": "git://github.com/numerique-gouv/ami-notifications-api.git",
                "ssh_url": "git@github.com:numerique-gouv/ami-notifications-api.git",
                "clone_url": "https://github.com/numerique-gouv/ami-notifications-api.git",
                "svn_url": "https://github.com/numerique-gouv/ami-notifications-api",
                "homepage": None,
                "size": 11018,
                "stargazers_count": 4,
                "watchers_count": 4,
                "language": "Python",
                "has_issues": True,
                "has_projects": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "has_discussions": False,
                "forks_count": 0,
                "mirror_url": None,
                "archived": False,
                "disabled": False,
                "open_issues_count": 103,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "spdx_id": "MIT",
                    "url": "https://api.github.com/licenses/mit",
                    "node_id": "MDc6TGljZW5zZTEz",
                },
                "allow_forking": True,
                "is_template": False,
                "web_commit_signoff_required": False,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 103,
                "watchers": 4,
                "default_branch": "main",
            },
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/83"
            },
            "html": {"href": "https://github.com/numerique-gouv/ami-notifications-api/pull/83"},
            "issue": {
                "href": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/83"
            },
            "comments": {
                "href": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/issues/83/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/83/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/pulls/83/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/numerique-gouv/ami-notifications-api/statuses/b9c987327a8f8e45648c1508faacf062637584c6"
            },
        },
        "author_association": "COLLABORATOR",
        "auto_merge": None,
        "active_lock_reason": None,
    },
]
