"""new already seen flag for User

Revision ID: 0157a02f787f
Revises: c44d0c9da2d7
Create Date: 2025-12-04 15:17:28.295027

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import true

# revision identifiers, used by Alembic.
revision: str = "0157a02f787f"
down_revision: Union[str, None] = "c44d0c9da2d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ami_user", sa.Column("already_seen", sa.Boolean(), nullable=False, server_default=true())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ami_user", "already_seen")
    # ### end Alembic commands ###
