"""last_logged_in

Revision ID: 07033155fefc
Revises: 2e9a48bafcfb
Create Date: 2025-12-19 15:36:37.061168

"""

from typing import Sequence, Union

import sqlalchemy as sa
from advanced_alchemy.types import DateTimeUTC
from alembic import op
from sqlalchemy.sql import true

# revision identifiers, used by Alembic.
revision: str = "07033155fefc"
down_revision: Union[str, None] = "2e9a48bafcfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ami_user", sa.Column("last_logged_in", DateTimeUTC(timezone=True), nullable=True)
    )
    op.execute(
        "UPDATE ami_user SET last_logged_in = updated_at WHERE last_logged_in is NULL AND already_seen is TRUE"
    )
    op.drop_column("ami_user", "already_seen")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ami_user", sa.Column("already_seen", sa.Boolean(), nullable=False, server_default=true())
    )
    op.execute("UPDATE ami_user SET already_seen = FALSE WHERE last_logged_in is NULL")
    op.drop_column("ami_user", "last_logged_in")
    # ### end Alembic commands ###
