"""remove User fields

Revision ID: 0ef4b60b7083
Revises: 18cc93cd264e
Create Date: 2025-12-01 15:22:03.420321

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ef4b60b7083"
down_revision: Union[str, None] = "18cc93cd264e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ami_user", "birthcountry")
    op.drop_column("ami_user", "gender")
    op.drop_column("ami_user", "family_name")
    op.drop_column("ami_user", "birthdate")
    op.drop_column("ami_user", "birthplace")
    op.drop_column("ami_user", "given_name")
    op.drop_column("ami_user", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ami_user", sa.Column("given_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "ami_user", sa.Column("birthplace", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column("ami_user", sa.Column("birthdate", sa.DATE(), autoincrement=False, nullable=True))
    op.add_column(
        "ami_user", sa.Column("family_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column("ami_user", sa.Column("gender", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "ami_user", sa.Column("birthcountry", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column("ami_user", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
