"""Registration label, enabled and created_at fields

Revision ID: 10d8c5919437
Revises: ed5c27a3498d
Create Date: 2025-06-30 10:58:22.228157

"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10d8c5919437"
down_revision: Union[str, None] = "ed5c27a3498d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "registration",
        sa.Column(
            "label", sa.VARCHAR(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
    )
    op.add_column(
        "registration", sa.Column("enabled", sa.Boolean(), nullable=False, server_default="0")
    )
    op.add_column(
        "registration",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=str(datetime.now())),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registration", "created_at")
    op.drop_column("registration", "enabled")
    op.drop_column("registration", "label")
    # ### end Alembic commands ###
