"""simplify registration model

Revision ID: 173bf68e90e0
Revises: bcfa2f59d108
Create Date: 2025-09-15 10:38:24.197513

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "173bf68e90e0"
down_revision: Union[str, None] = "bcfa2f59d108"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registration", "label")
    op.drop_column("registration", "enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registration",
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "registration",
        sa.Column(
            "label", sa.VARCHAR(), server_default="label", autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
