"""fc_hash for User

Revision ID: 18cc93cd264e
Revises: f3da16766119
Create Date: 2025-12-01 09:29:02.543496

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.utils import build_fc_hash

# revision identifiers, used by Alembic.
revision: str = "18cc93cd264e"
down_revision: Union[str, None] = "f3da16766119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ami_user", sa.Column("fc_hash", sa.String(), nullable=True))
    # generate fc_hash
    connection = op.get_bind()
    meta = sa.MetaData()
    user = sa.Table(
        "ami_user",
        meta,
        autoload_with=connection,
    )

    res = connection.execute(user.select())
    results = res.fetchall()
    for row in results:
        row_dict = row._asdict()  # type: ignore[reportPrivateUsage]
        fc_hash = build_fc_hash(
            given_name=row_dict["given_name"] or "",
            family_name=row_dict["family_name"] or "",
            birthdate=row_dict["birthdate"].isoformat() if row_dict["birthdate"] else "",
            gender=row_dict["gender"] or "",
            birthplace=str(row_dict["birthplace"]) if row_dict["birthplace"] else "",
            birthcountry=str(row_dict["birthcountry"]) if row_dict["birthcountry"] else "",
        )
        connection.execute(user.update().where(user.c.id == row_dict["id"]).values(fc_hash=fc_hash))
    op.alter_column("ami_user", "fc_hash", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(op.f("uq_ami_user_fc_hash"), "ami_user", ["fc_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_ami_user_fc_hash"), "ami_user", type_="unique")
    op.drop_column("ami_user", "fc_hash")
    # ### end Alembic commands ###
