"""scheduled notification

Revision ID: 2e9a48bafcfb
Revises: d61d083e808d
Create Date: 2025-12-11 14:46:27.247033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from advanced_alchemy.types import GUID, DateTimeUTC
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e9a48bafcfb"
down_revision: Union[str, None] = "d61d083e808d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_notification",
        sa.Column("user_id", GUID(length=16), nullable=False),
        sa.Column("content_title", sa.String(), nullable=False),
        sa.Column("content_body", sa.String(), nullable=False),
        sa.Column("content_icon", sa.String(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("scheduled_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("sent_at", DateTimeUTC(timezone=True), nullable=True),
        sa.Column("id", GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["ami_user.id"], name=op.f("fk_scheduled_notification_user_id_ami_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_notification")),
    )
    op.create_unique_constraint(
        "uix_user_reference", "scheduled_notification", ["user_id", "reference"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_user_reference", "scheduled_notification", type_="unique")
    op.drop_table("scheduled_notification")
    # ### end Alembic commands ###
