"""notification try_push

Revision ID: 32b61eb977b7
Revises: 07033155fefc
Create Date: 2026-01-22 11:23:29.677216

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32b61eb977b7"
down_revision: Union[str, None] = "07033155fefc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("try_push", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "try_push")
    # ### end Alembic commands ###
