"""revoked auth token

Revision ID: 48d3169f15b5
Revises: b58f3c00a8ce
Create Date: 2026-02-23 15:51:19.527870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from advanced_alchemy.types import GUID, DateTimeUTC
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48d3169f15b5"
down_revision: Union[str, None] = "b58f3c00a8ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_auth_token",
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("id", GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revoked_auth_token")),
        sa.UniqueConstraint("jti", name=op.f("uq_revoked_auth_token_jti")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("revoked_auth_token")
    # ### end Alembic commands ###
