"""remove unknown user's notifications

Revision ID: 4e2286464dc4
Revises: b58f3c00a8ce
Create Date: 2026-02-23 16:12:18.033211

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e2286464dc4"
down_revision: Union[str, None] = "48d3169f15b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE from notification WHERE user_id IN (SELECT id FROM ami_user WHERE last_logged_in IS NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
