"""Remove unused registration.enabled and registration.label

Revision ID: 6ef068ae88ad
Revises: 835a33f620e1
Create Date: 2025-10-08 16:04:32.249910

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ef068ae88ad"
down_revision: Union[str, None] = "835a33f620e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registration", "label")
    op.drop_column("registration", "enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registration",
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "registration", sa.Column("label", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
