"""Add FC user info to the ami_user table

Revision ID: 835a33f620e1
Revises: 10d8c5919437
Create Date: 2025-10-07 14:27:11.965263

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "835a33f620e1"
down_revision: Union[str, None] = "10d8c5919437"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ami_user", sa.Column("birthcountry", sa.Integer(), nullable=True))
    op.add_column("ami_user", sa.Column("birthdate", sa.Date(), nullable=True))
    op.add_column("ami_user", sa.Column("birthplace", sa.Integer(), nullable=True))
    op.add_column("ami_user", sa.Column("family_name", sa.VARCHAR(), nullable=True))
    op.add_column("ami_user", sa.Column("gender", sa.VARCHAR(), nullable=True))
    op.add_column("ami_user", sa.Column("given_name", sa.VARCHAR(), nullable=True))
    op.alter_column("ami_user", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ami_user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("ami_user", "given_name")
    op.drop_column("ami_user", "gender")
    op.drop_column("ami_user", "family_name")
    op.drop_column("ami_user", "birthplace")
    op.drop_column("ami_user", "birthdate")
    op.drop_column("ami_user", "birthcountry")
    # ### end Alembic commands ###
