"""notification partner_id

Revision ID: a35a64f78ede
Revises: b58f3c00a8ce
Create Date: 2026-02-06 15:32:54.796312

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a35a64f78ede"
down_revision: Union[str, None] = "b58f3c00a8ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("partner_id", sa.String(), nullable=True))
    op.execute("""
        UPDATE notification
        SET partner_id = 'psl' where sender = 'PSL'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "partner_id")
    # ### end Alembic commands ###
