"""notification send_status

Revision ID: b58f3c00a8ce
Revises: 32b61eb977b7
Create Date: 2026-02-03 21:25:02.086192

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b58f3c00a8ce"
down_revision: Union[str, None] = "32b61eb977b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("send_status", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "send_status")
    # ### end Alembic commands ###
