"""add_userinfo_in_user

Revision ID: bcfa2f59d108
Revises: 10d8c5919437
Create Date: 2025-09-11 17:25:19.196443

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcfa2f59d108"
down_revision: Union[str, None] = "10d8c5919437"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donneespivot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("given_name", sa.VARCHAR(), nullable=False),
        sa.Column("family_name", sa.VARCHAR(), nullable=False),
        sa.Column("birthdate", sa.DateTime(), nullable=False),
        sa.Column("gender", sa.VARCHAR(), nullable=False),
        sa.Column("birthplace", sa.Integer(), nullable=False),
        sa.Column("birthcountry", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["ami_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.alter_column("ami_user", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ami_user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table("donneespivot")
    # ### end Alembic commands ###
