"""new notification fields

Revision ID: c44d0c9da2d7
Revises: 0ef4b60b7083
Create Date: 2025-12-01 16:40:44.186196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from advanced_alchemy.types.datetime import DateTimeUTC
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c44d0c9da2d7"
down_revision: Union[str, None] = "0ef4b60b7083"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification") as batch_op:
        batch_op.alter_column("title", new_column_name="content_title")
        batch_op.alter_column("message", new_column_name="content_body")
        batch_op.add_column(sa.Column("content_icon", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("item_type", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("item_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("item_status_label", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("item_generic_status", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("item_canal", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("item_milestone_start_date", DateTimeUTC(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("item_milestone_end_date", DateTimeUTC(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("item_external_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("send_date", DateTimeUTC(timezone=True), nullable=True))
    op.execute("UPDATE notification SET send_date = created_at WHERE send_date is NULL")
    op.execute("UPDATE notification SET content_title = '' WHERE content_title is NULL")
    op.execute("UPDATE notification SET sender = '' WHERE sender is NULL")
    with op.batch_alter_table("notification") as batch_op:
        batch_op.alter_column("send_date", nullable=False)
        batch_op.alter_column("content_title", nullable=False)
        batch_op.alter_column("sender", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification") as batch_op:
        batch_op.alter_column("content_title", new_column_name="title", nullable=True)
        batch_op.alter_column("content_body", new_column_name="message")
        batch_op.alter_column("sender", nullable=True)
        batch_op.drop_column("send_date")
        batch_op.drop_column("item_external_url")
        batch_op.drop_column("item_milestone_end_date")
        batch_op.drop_column("item_milestone_start_date")
        batch_op.drop_column("item_canal")
        batch_op.drop_column("item_generic_status")
        batch_op.drop_column("item_status_label")
        batch_op.drop_column("item_id")
        batch_op.drop_column("item_type")
        batch_op.drop_column("content_icon")
    # ### end Alembic commands ###
