"""models from UUIDAuditBase

Revision ID: c53e6dd539a0
Revises: 291953dacae4
Create Date: 2025-10-30 14:58:47.628803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from advanced_alchemy.types import GUID, DateTimeUTC
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c53e6dd539a0"
down_revision: Union[str, None] = "291953dacae4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # user - add new columns
    with op.batch_alter_table("ami_user") as batch_op:
        batch_op.add_column(sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("created_at", DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("uuid", GUID(length=16), nullable=True))
    op.execute("UPDATE ami_user SET created_at = now() WHERE created_at is NULL")
    op.execute("UPDATE ami_user SET updated_at = now() WHERE updated_at is NULL")
    op.execute("UPDATE ami_user SET uuid = gen_random_uuid() WHERE uuid is NULL")
    with op.batch_alter_table("ami_user") as batch_op:
        batch_op.alter_column("created_at", nullable=False)
        batch_op.alter_column("updated_at", nullable=False)
        batch_op.alter_column("uuid", nullable=False)

    # notification - add new columns
    with op.batch_alter_table("notification") as batch_op:
        batch_op.add_column(sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("uuid", GUID(length=16), nullable=True))
    op.execute("UPDATE notification SET updated_at = now() WHERE updated_at is NULL")
    op.execute("UPDATE notification SET uuid = gen_random_uuid() WHERE uuid is NULL")
    with op.batch_alter_table("notification") as batch_op:
        batch_op.alter_column("updated_at", nullable=False)
        batch_op.alter_column("uuid", nullable=False)
        # and rename column date
        batch_op.alter_column("date", new_column_name="created_at")

    # registration - add new columns
    with op.batch_alter_table("registration") as batch_op:
        batch_op.add_column(sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", DateTimeUTC(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("uuid", GUID(length=16), nullable=True))
    op.execute("UPDATE registration SET updated_at = now() WHERE updated_at is NULL")
    op.execute("UPDATE registration SET uuid = gen_random_uuid() WHERE uuid is NULL")
    with op.batch_alter_table("registration") as batch_op:
        batch_op.alter_column("updated_at", nullable=False)
        batch_op.alter_column("uuid", nullable=False)

    # registration - new pk type uuid
    with op.batch_alter_table("registration") as batch_op:
        batch_op.drop_column("id")  # sequence and pk constraint are automatically dropped
        batch_op.alter_column("uuid", new_column_name="id")
        batch_op.create_primary_key("registration_pkey", ["id"])

    # notification - new pk type uuid
    with op.batch_alter_table("notification") as batch_op:
        batch_op.drop_column("id")  # sequence and pk constraint are automatically dropped
        batch_op.alter_column("uuid", new_column_name="id")
        batch_op.create_primary_key("notification_pkey", ["id"])

    # new user_id columns type uuid
    op.add_column("notification", sa.Column("user_uuid", GUID(length=16), nullable=True))
    op.execute(
        "UPDATE notification AS n SET user_uuid = u.uuid FROM ami_user AS u WHERE n.user_uuid is NULL AND n.user_id = u.id"
    )
    with op.batch_alter_table("notification") as batch_op:
        batch_op.drop_column("user_id")  # fk constraint is automatically dropped
        batch_op.alter_column("user_uuid", new_column_name="user_id", nullable=False)
    op.add_column("registration", sa.Column("user_uuid", GUID(length=16), nullable=True))
    op.execute(
        "UPDATE registration AS n SET user_uuid = u.uuid FROM ami_user AS u WHERE n.user_uuid is NULL AND n.user_id = u.id"
    )
    with op.batch_alter_table("registration") as batch_op:
        batch_op.drop_column("user_id")  # fk constraint is automatically dropped
        batch_op.alter_column("user_uuid", new_column_name="user_id", nullable=False)

    # user - new pk type uuid
    with op.batch_alter_table("ami_user") as batch_op:
        batch_op.drop_column("id")  # sequence and pk constraint are automatically dropped
        batch_op.alter_column("uuid", new_column_name="id")
        batch_op.create_primary_key("user_pkey", ["id"])
    with op.batch_alter_table("notification") as batch_op:
        batch_op.create_foreign_key(
            "fk_notification_user_id_ami_user", "ami_user", ["user_id"], ["id"]
        )
    with op.batch_alter_table("registration") as batch_op:
        batch_op.create_foreign_key(
            "fk_registration_user_id_ami_user", "ami_user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # user - old pk type int
    with op.batch_alter_table("notification") as batch_op:
        batch_op.drop_constraint("fk_notification_user_id_ami_user")
    with op.batch_alter_table("registration") as batch_op:
        batch_op.drop_constraint("fk_registration_user_id_ami_user")
    with op.batch_alter_table("ami_user") as batch_op:
        batch_op.drop_constraint("user_pkey")
        batch_op.alter_column("id", new_column_name="uuid")
    op.execute("CREATE SEQUENCE user_id_seq")
    with op.batch_alter_table("ami_user") as batch_op:
        batch_op.add_column(
            sa.Column(
                "id", sa.Integer(), server_default=sa.text("nextval('user_id_seq')"), nullable=False
            )
        )
    op.execute("ALTER SEQUENCE user_id_seq OWNED BY ami_user.id")
    with op.batch_alter_table("ami_user") as batch_op:
        batch_op.create_primary_key("user_pkey", ["id"])

    # old user_id columns type int
    op.add_column("notification", sa.Column("user_intid", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE notification AS n SET user_intid = u.id FROM ami_user AS u WHERE n.user_intid is NULL AND n.user_id = u.uuid"
    )
    with op.batch_alter_table("notification") as batch_op:
        batch_op.drop_column("user_id")  # fk constraint is automatically dropped
        batch_op.alter_column("user_intid", new_column_name="user_id", nullable=False)
        batch_op.create_foreign_key(
            "fk_registration_user_id_ami_user", "ami_user", ["user_id"], ["id"]
        )
    op.add_column("registration", sa.Column("user_intid", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE registration AS n SET user_intid = u.id FROM ami_user AS u WHERE n.user_intid is NULL AND n.user_id = u.uuid"
    )
    with op.batch_alter_table("registration") as batch_op:
        batch_op.drop_column("user_id")  # fk constraint is automatically dropped
        batch_op.alter_column("user_intid", new_column_name="user_id", nullable=False)
        batch_op.create_foreign_key(
            "fk_registration_user_id_ami_user", "ami_user", ["user_id"], ["id"]
        )

    # notification - old pk type int
    with op.batch_alter_table("notification") as batch_op:
        batch_op.drop_constraint("notification_pkey")
        batch_op.alter_column("id", new_column_name="uuid")
    op.execute("CREATE SEQUENCE notification_id_seq")
    with op.batch_alter_table("notification") as batch_op:
        batch_op.add_column(
            sa.Column(
                "id",
                sa.Integer(),
                server_default=sa.text("nextval('notification_id_seq')"),
                nullable=False,
            )
        )
    op.execute("ALTER SEQUENCE notification_id_seq OWNED BY notification.id")
    with op.batch_alter_table("notification") as batch_op:
        batch_op.create_primary_key("notification_pkey", ["id"])

    # registration - old pk type int
    with op.batch_alter_table("registration") as batch_op:
        batch_op.drop_constraint("registration_pkey")
        batch_op.alter_column("id", new_column_name="uuid")
    op.execute("CREATE SEQUENCE registration_id_seq")
    with op.batch_alter_table("registration") as batch_op:
        batch_op.add_column(
            sa.Column(
                "id",
                sa.Integer(),
                server_default=sa.text("nextval('registration_id_seq')"),
                nullable=False,
            )
        )
    op.execute("ALTER SEQUENCE registration_id_seq OWNED BY registration.id")
    with op.batch_alter_table("registration") as batch_op:
        batch_op.create_primary_key("registration_pkey", ["id"])

    # registration - drop new columns
    with op.batch_alter_table("registration") as batch_op:
        batch_op.drop_column("uuid")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("sa_orm_sentinel")

    # notification - drop new columns
    with op.batch_alter_table("notification") as batch_op:
        batch_op.drop_column("uuid")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("sa_orm_sentinel")
        # and rename column created_at
        batch_op.alter_column("created_at", new_column_name="date")

    # user - drop new columns
    with op.batch_alter_table("ami_user") as batch_op:
        batch_op.drop_column("uuid")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("sa_orm_sentinel")

    # ### end Alembic commands ###
