"""notification read flag

Revision ID: d61d083e808d
Revises: 0157a02f787f
Create Date: 2025-12-08 10:45:56.130443

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import true

# revision identifiers, used by Alembic.
revision: str = "d61d083e808d"
down_revision: Union[str, None] = "0157a02f787f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification") as batch_op:
        batch_op.add_column(sa.Column("read", sa.Boolean(), nullable=True))
    op.execute("UPDATE notification SET read = not unread WHERE read is NULL")
    with op.batch_alter_table("notification") as batch_op:
        batch_op.alter_column("read", nullable=False)
        batch_op.drop_column("unread")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification") as batch_op:
        batch_op.add_column(
            sa.Column(
                "unread", sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=true()
            )
        )
        batch_op.drop_column("read")
    # ### end Alembic commands ###
