"""notification add unread field

Revision ID: efc4f6e39a83
Revises: 6ef068ae88ad
Create Date: 2025-10-14 16:47:27.283329

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efc4f6e39a83"
down_revision: Union[str, None] = "6ef068ae88ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("unread", sa.Boolean(), nullable=True))
    op.execute("""
        UPDATE notification
        SET unread = true
    """)
    op.alter_column("notification", "unread", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "unread")
    # ### end Alembic commands ###
