# Generated by Django 6.0.5 on 2026-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0009_partner_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="content_private_body",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="content_private_body",
            field=models.CharField(blank=True, null=True),
        ),
    ]
