# Generated by Django 6.0.5 on 2026-05-28 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0010_add_content_private_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulednotification",
            name="content_private_body",
        ),
    ]
