# Generated by Django 6.0.4 on 2026-05-04 08:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="AnonymizedUser",
            name="original_id",
        ),
        migrations.AddField(
            model_name="AnonymizedUser",
            name="replication_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="AnonymizedUser",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="AnonymizedUser",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
