# Generated by Django 6.0.5 on 2026-06-01 13:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replication", "0005_anonymizednotification_anonymizedregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymizeduser",
            name="replication_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
