# Generated by Django 6.0.5 on 2026-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replication", "0006_alter_anonymizeduser_replication_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymizedregistration",
            name="subscription",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
