# Generated by Django 6.0.7 on 2026-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0003_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="ip_allow_list",
            field=models.TextField(blank=True),
        ),
    ]
