name: Tests
on: [push]
jobs:

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - run: make lint-and-format

  run-tests:
    name: python
    runs-on: ubuntu-latest
    needs: [lint-and-format]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: make test

  mobile-app-tests:
    name: mobile-app
    runs-on: ubuntu-latest
    needs: [lint-and-format]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'public/mobile-app/package-lock.json'

      - name: Install dependencies
        working-directory: ./public/mobile-app
        run: npm ci

      - name: Create .env file
        run: cp .env.template .env

      - name: Install Playwright Browsers
        working-directory: ./public/mobile-app
        run: npx playwright install --with-deps

      - name: Run tests
        working-directory: ./public/mobile-app
        run: npm test
