name: workflow-e2e-webapp.yml
on:
  # Se lance en local avec :
  # act workflow_dispatch -W .github/workflows/notification-api.pull-request.yml --container-architecture linux/amd64 --artifact-server-path /tmp/act-artifacts --input source_repo="my-test-repo" --input pr_number=123456789
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Simule github.event.pull_request.number — 0 pour simuler un push/tag sans PR"
        type: number
        default: 0
      run_webapp:
        description: "demande à lancer une suite de test sur la Webapp Scalingo"
        type: boolean
        default: true
      run_android:
        description: "demande à lancer une suite de test sur l'apk Android'"
        type: boolean
        default: false
      run_ios:
        description: "demande à lancer une suite de test sur l'app iOS'"
        type: boolean
        default: false
      run_old_device:
        description: "demande à lancer une suite de test mobile avec la configuration la plus ancienne disponible"
        type: boolean
        default: true

jobs:
  # Pas de job `build` ici, contrairement à l'exemple ami-app-android : l'app webapp testée vient
  # des stores beta (Google Play / TestFlight), pas d'un artefact buildé par ce workflow.
  e2e-launch:
    name: trigger an e2e run in ami-system-tests
    uses: numerique-gouv/ami-system-tests/.github/workflows/workflow-e2e-main.yml@10-ci-api-ios-android-wip
    with:
      ref_name: staging
      run_webapp: true
      run_android: false
      run_ios: false
      run_old_device: true
      source_repo: ${{ github.repository }}
      pr_number: ${{ fromJSON(inputs.pr_number) }}
      checkout_ref: 10-ci-api-ios-android-wip # la même branche/ref que uses de préférence
    secrets: inherit

  e2e-report:
    name: uses output of e2e run in ami-system-tests to report in pr
    needs: e2e-launch
    runs-on: ubuntu-latest
    if: ${{ always() }}
    permissions:
      pull-requests: write
      checks: write
    steps:
      - name: Charger le rapport de test pour le mettre dans la PR
        if: ${{ fromJSON(inputs.pr_number) != 0 }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.e2e-launch.outputs.allure_report }}
          path: ami-system-tests/allure-report

      - name: Commenter la PR d'origine
        if: ${{ fromJSON(inputs.pr_number) != 0 }}
        uses: allure-framework/allure-action@v0
        with:
          report-directory: ami-system-tests/allure-report
          github-token: ${{ github.token }}

      - name: logguer l'url du rapport de tests
        if: ${{ always() }}
        run: echo -e "Le rapport de tests est téléchargeable à l'adresse:\n\t${{ needs.e2e-launch.outputs.allure_report }}"
