name: workflow-e2e-webapp.yml
on:
  # Se lance en local avec :
  # act workflow_dispatch -W .github/workflows/notification-api.pull-request.yml --container-architecture linux/amd64 --artifact-server-path /tmp/act-artifacts --input source_repo="my-test-repo" --input pr_number=123456789
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Simule github.event.pull_request.number — 0 pour simuler un push/tag sans PR"
        type: number
        default: 0
      run_webapp:
        description: "demande à lancer une suite de test sur la Webapp Scalingo"
        type: boolean
        default: true
      run_android:
        description: "demande à lancer une suite de test sur l'apk Android'"
        type: boolean
        default: false
      run_ios:
        description: "demande à lancer une suite de test sur l'app iOS'"
        type: boolean
        default: false
      run_old_device:
        description: "demande à lancer une suite de test mobile avec la configuration la plus ancienne disponible"
        type: boolean
        default: true

jobs:
  # Pas de job `build` ici, contrairement à l'exemple ami-app-android : l'app webapp testée vient
  # des stores beta (Google Play / TestFlight), pas d'un artefact buildé par ce workflow.
  e2e-launch:
    name: trigger an e2e run in ami-system-tests
    uses: numerique-gouv/ami-system-tests/.github/workflows/workflow-e2e-main.yml@10-ci-api-ios-android-wip
    with:
      ref_name: staging
      run_webapp: true
      run_android: false
      run_ios: false
      run_old_device: true
      source_repo: ${{ github.repository }}
      pr_number: ${{ fromJSON(inputs.pr_number) }}
    secrets: inherit

  e2e-report:
    name: uses output of e2e run in ami-system-tests to report in current repo
    needs: e2e-launch
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -e "received out_ref_name=${{ needs.e2e-launch.outputs.out_ref_name }}\n and out_webapp=${{ needs.e2e-launch.outputs.out_webapp }}"
